#!/bin/bash

in=${!##\\input } # ${!#} is the last argument
job=${in%.*}

case "$in" in
	*.tex) cp --verbose -- "$in" "$job.pdf"; exit $? ;;
	*.sh) source "$in" >"$job.dryrun.log"; exit $? ;;
	*.jam) ;;
	*) echo "Wrong usage of $0"; exit 1 ;;
esac

out="$job.pdf"
pdfjam="./pdfjam --latex $(realpath "$0") --vanilla --build-dir '$job.d' --outfile '$out'"

case "$job" in
	*.sh) source "$in" ;;
	*) eval "$pdfjam $(< "$in")" ;;
esac
