#!/bin/bash

in=${!##\\input } # ${!#} is the last argument
job=${in%.jam}
out="$job.pdf"

tex=a
case "$0" in
	*engine-pdf|*engine-xe|*engine-lua)
		tex=${0##*-}
		latex=" --latex $(command -v "${tex}latex")"
		;;
	*engine) ;;
	*) echo "name $0 unexpected"; exit 1
esac
dir="$tex/$job.d"

pdfjam="./pdfjam$latex --vanilla --build-dir '$dir' --outfile '$out' --preamble '"\
'\input{regression-test.tex}\AtBeginDocument{\START}'\'

case "$job" in
	*.sh) source "$in" ;;
	*) eval "$pdfjam $(< "$in")" ;;
esac

<"$dir/a.log" awk '/^ *\[[0-9]+/{ORS=""} /\]/{ORS="\n"}
/^END-TEST-LOG$/{system("TZ=UTC pdfinfo '"$dir/a.pdf"'")}
//' \
	| sed '/^ *\[[0-9]\+/s/ //g
		s/\.\([0-9]\{3\}\)[0-9]*pt/.\1pt/g
		s/luatex\.def/pdftex.def/
		/^<\(source-[0-9]*\|stdin\).pdf,/s/id=[0-9]*/id=00/
		s/^\(Producer:        \).*$/\1TeXengine/
		s/^\(File size:       \)[0-9]\{4,\} bytes/\10000 bytes/
		' \
	>"$job.log"
